---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: guestbook-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guestbook-app-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu 
        targetAverageUtilization: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app-deployment
  labels:
    app: guestbook-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-app
  template:
    metadata:
      labels:
        app: guestbook-app
    spec:
      containers:
        - name: guestbook-app
          image: ruanbekker/flask-mysql-guestbook:nunito
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-app-credentials-ga
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-app-credentials-ga
                  key: password
            - name: FLASK_APP
              value: application
            - name: MYSQL_DATABASE
              value: guestbook
            - name: MYSQL_HOST
              value: mysqlcluster.default.svc.cluster.local
      initContainers:
        - name: db-script
          image: archangel91/init-db:latest
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-app-credentials-ga
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-app-credentials-ga
                  key: password
            - name: MYSQL_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials-ga
                  key: username
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials-ga
                  key: password
            - name: MYSQL_DATABASE
              value: guestbook
            - name: MYSQL_HOST
              value: mysqlcluster.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: guestbook-app
  type: LoadBalancer
