name: Deploy to EKS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    #   - name: Configure kubectl
    #     uses: aws-actions/configure-aws-credentials@v1
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: ca-central-1
      - name: Install kubectl
        run: |
          curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.17/2023-01-30/bin/linux/amd64/kubectl
          echo "Kubectl Download Completed"
          chmod +x ./kubectl
          echo "Moving Kubectl"
          sudo mv kubectl /bin/
          echo "Preparing Kubeconfig"
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > kubeconfig.yaml
      - name: Set MYSQL Root Secrets
        uses: azure/k8s-create-secret@v4
        with:
           namespace: 'default'
           secret-name: 'mysql-app-credentials-ga'
           username: ${{ secrets.mysql_app_username }}
           password: ${{ secrets.mysql_app_password }}
      - name: Set MYSQL App Secrets
        uses: azure/k8s-create-secret@v4
        with:
           namespace: 'default'
           secret-name: 'mysql-root-credentials-ga'
           username: ${{ secrets.mysql_root_username }}
           password: ${{ secrets.mysql_root_password }}
      - name: Deploy
        run: kubectl apply -f  guestbook-githubactions/main.yml
